services:
  # Serviço 1: API (Backend)
  api:
    build: .
    container_name: juscash-api
    # Sobrescreve o CMD do Dockerfile para rodar apenas a API
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # Configuração para LangSmith (Opcional)
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
    networks:
      - juscash-network
    volumes:
      # Monta o código local dentro do container para "Hot Reload" (alterou o código, atualiza na hora)
      - ./app:/app

  # Serviço 2: Interface Visual (Frontend)
  ui:
    build: .
    container_name: juscash-ui
    # Sobrescreve o CMD para rodar apenas o Streamlit
    command: streamlit run frontend/ui.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "80:8501"
    env_file:
      - .env
    environment:
      # A UI precisa saber onde a API está. Dentro da rede Docker, usamos o nome do serviço 'api'
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - juscash-network
    volumes:
      - ./app:/app

networks:
  juscash-network:
    driver: bridge

volumes:
  n8n_data: